---
subtitle: "Decision Tree algorithm"
title: 'Diabetes predictor'
author: "Sergio Carracedo Huroz"
date: 'July 2022'
output:
  bookdown::html_document2:
    toc: no
    toc_depth: 3
    base_format: prettydoc::html_pretty
  html_document:
    toc: yes
  bookdown::pdf_document2:
    df_print: paged
    toc: yes
    toc_depth: '3'
    extra_dependencies: float
  pdf_document:
    toc: yes
    toc_depth: '2'
header-includes:
 \usepackage{float}
 \floatplacement{figure}{H}
nocite: |
  @lantz2015machine
link-citations: yes
bibliography: scholar1.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA, message = FALSE, warning = FALSE)
```

```{r}
# Importing libraries
library(randomForest)
library(kableExtra)
library(dplyr)
library(caret)
library(C50) # Decision tree

# Set working directory
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
```


#### Summary of data used to build Decision tree model
```{r }
# Importing the df dataset
df <- read.csv("diabetes.txt", stringsAsFactors = TRUE)
# knitr::kable(summary(df)) %>%   kable_styling(font_size = 12)
summary(df)
```


```{r }
## Decision Tree model

# Set working directory
setwd(dirname(rstudioapi::getSourceEditorContext()$path))


# Read in the Decision tree model
model <- readRDS("model.rds")

#Read data
TestingSet <- read.csv("testing.csv", header = TRUE, stringsAsFactors = TRUE)
TestingSet <- TestingSet[,-1]


# Model predictions
model.predict <- predict(model,TestingSet) 
```

#### Algorithm performance
```{r }

# Model Performance
(model.performance <- confusionMatrix(data = model.predict ,
                reference = TestingSet$diabetes))
```

### References


