---
title: ' '
subtitle: ""

author: ""
date: ''
output:
  html_document:
    df_print: paged
    toc: no
header-includes:
 \usepackage{float}
 \floatplacement{figure}{H}
nocite: |
  @lantz2015machine
link-citations: yes
bibliography: scholar1.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA, message = FALSE, warning = FALSE)
```

```{r }
# Importing libraries
library(randomForest)
library(kableExtra)
library(dplyr)
library(caret)
library(C50) # Decision tree


# Set working directory
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
```



### **Summary of predictors in *diabetes* dataset**
```{css}
.main-container {
    max-width: 100%;
}
```
```{r }
# Importing the df dataset
df <- read.csv("diabetes.txt", stringsAsFactors = TRUE)

# knitr::kable(summary(df)) %>%   kable_styling(font_size = 12)

a <-as.data.frame(apply(df[1:8],2,summary))
kable(a, "html") %>%   kable_styling(full_width = F, position = "left")
```

<!---### Decision Tree model---> 

```{r results='hide'}
# Set working directory
setwd(dirname(rstudioapi::getSourceEditorContext()$path))


# Read in the Decision tree model
model_diabetes <- readRDS("model_diabetes.rds")

#Read data
TestingSet <- read.csv("testing_diabetes.csv", header = TRUE, stringsAsFactors = TRUE)
TestingSet <- TestingSet[,-1]


# Model predictions
model.predict <- predict(model_diabetes,TestingSet) 
model.predict
```

<!---### Algorithm performance---> 
```{r results='hide'}

# Model Performance
(model.performance <- confusionMatrix(data = model.predict ,
                reference = TestingSet$diabetes))
```

```{r}
```

### **References**


